[[redirects]]
  from = "/api/*"
  to = "https://jayneet639.pythonanywhere.com/api"
  status = 200
[[redirects]]
  from = "/users/*"
  to = "https://jayneet639.pythonanywhere.com/users"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200